#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.
image: maven:3.6-jdk-11

pipelines:
  tags:
    '*':
      - step:
          name: Build and Deploy tag
          caches:
            - maven
          script:
            - mvn -B -Daws.accessKeyId="$MAVEN_USER" -Daws.secretKey="$MAVEN_PASSWORD" -DskipITs deploy
  branches:
    master:
      - step:
          name: Build and Deploy
          caches:
            - maven
          script:
            - mvn -B -Daws.accessKeyId="$MAVEN_USER" -Daws.secretKey="$MAVEN_PASSWORD" -DskipITs deploy