name: CI

on:
  push:
    paths:
      - '**/*.java'
      - 'pom.xml'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BYTEBUDDY_VERSION: 1.17.5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download ByteBuddy agent for tests
      run: mvn -B dependency:copy -Dartifact=net.bytebuddy:byte-buddy-agent:${{ env.BYTEBUDDY_VERSION }} -DoutputDirectory=target/test-agent -Dtransitive=false

    - name: Run unit tests
      run: mvn -B -DargLine="-javaagent=${{ github.workspace }}/target/test-agent/byte-buddy-agent-${{ env.BYTEBUDDY_VERSION }}.jar" test
